### ISSUE TITLE
超出一屏后都挤在最后一行咋办

### ISSUE THREAD

**Issue by xgz123** [qianlnk/pgbar#1]
比如我有100个， 前9个正常，后面91个都挤在最后一行交替出现

**Comment by qianlnk** [comment]
@xgz123 光标应该只支持在本屏内移动，所以超出的应该没有办法，  你可以选择将这个工具改成双屏的，一行输出两个进度条。

**Comment by xgz123** [comment]
@qianlnk 是个办法，但文件很多的话还是会有这个问题。我考虑达到某个值后清空。

**Comment by shanghai-Jerry** [comment]
"github.com/qianlnk/to" where is it

**Comment by qianlnk** [comment]
@shanghai-Jerry 一些特殊原因被我下掉了   补上去了
