### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by iwctwbai** [qianlnk/pgbar#5]
报错信息：
goroutine 383 [running]:
github.com/qianlnk/pgbar.(*Bar).Add(0xc006186000, {0xc000f4a6b0, 0x10, 0xc000f43b5f})

看下此处是否需要处理下 我这边修改后无误
```
github.com/qianlnk/pgbar@v0.0.0-20210208085217-8c19b9f2477e/bar.go:114 

if (lastRate != b.rate || lastSpeed != b.speed) && !b.closed  {
    b.advance <- true
}
```

**Comment by qianlnk** [comment]
@iwctwbai 有panic用例么，这里按理来说除非100%后还调用Add才会panic
